# Generated by Django 5.2 on 2025-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_education_alter_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('not_chosen', 'انتخاب کنید'), ('diploma', 'دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس')], default='master', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('not_chosen', 'انتخاب کنید'), ('student', 'دانشجو'), ('engineering', 'مهندس'), ('teacher', 'معلم')], max_length=20),
        ),
    ]
